version: '2'
services:
  minecraft-server:
    ports:
      - "25565:25565"

    environment:
      EULA: "TRUE"
      VERSION: "SNAPSHOT"

    image: itzg/minecraft-server

    container_name: mc

    tty: true
    stdin_open: true
    restart: always

    volumes:
      - files:/data

volumes:
  files:

